### PR TITLE
Update push notification key for iOS

### PR DESCRIPTION
**Pull request by hellais**
@lorenzoPrimi are changes related to the iOS push notification keys still necessary?

### CODE REVIEW

**Comment by lorenzoPrimi** [comment]
is this a new certificate? so yes

**Comment by darkk** [comment]
Was it rolled out? Should it be merged or discarded?

**Comment by hellais** [comment]
@lorenzoPrimi if you still need this please ping me on slack about it and let's do it together.

**Comment by hellais** [comment]
It was not rolled out or deployed.

**Pull request closed without merging**
